### ISSUE TITLE
Fix Same Site Cookie Policy

### ISSUE THREAD

**Issue by egortaran** [soshace/fosterflow#70]
Time to fix : 1 hour
If we use 'localhost' Cookies stored, but if we change to 127.0.0.1 Cookies not working.
Try find answer on Same Site Cookie Policy with var AUTH_COOKIE_SAMESITE

**Comment by brnikita** [comment]
In our case CORS doesn't work at all. Could you fully remove this option from the project?
![397dee597c](https://github.com/soshace/fosterflow/assets/761219/0dc2f7a5-626e-4211-93d3-0bc0896f3a34)
